"""Add tour company complete models with gallery packages discounts and documents

Revision ID: 2608ca629f84
Revises: e4cca3947e7c
Create Date: 2026-04-30 19:57:24.691306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2608ca629f84'
down_revision = 'e4cca3947e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('verification_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('business_registration_doc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tax_compliance_doc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('insurance_certificate', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('license_document', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('additional_documents', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deletion_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deletion_requested_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deletion_scheduled_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key('fk_tour_companies_deletion_requested_by', 'users', ['deletion_requested_by'], ['id'])
        batch_op.create_foreign_key('fk_tour_companies_verified_by', 'users', ['verified_by'], ['id'])

    with op.batch_alter_table('tour_company_images', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tour_company_reviews', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_company_reviews', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tour_company_images', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tour_companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tour_companies_deletion_requested_by', type_='foreignkey')
        batch_op.drop_constraint('fk_tour_companies_verified_by', type_='foreignkey')
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('deletion_scheduled_date')
        batch_op.drop_column('deletion_requested_by')
        batch_op.drop_column('deletion_requested_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('additional_documents')
        batch_op.drop_column('license_document')
        batch_op.drop_column('insurance_certificate')
        batch_op.drop_column('tax_compliance_doc')
        batch_op.drop_column('business_registration_doc')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('verification_notes')
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###