"""Add social media fields to tour companies

Revision ID: e4cca3947e7c
Revises: 
Create Date: 2026-04-30 14:50:00.932354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cca3947e7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('youtube', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tiktok', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_companies', schema=None) as batch_op:
        batch_op.drop_column('tiktok')
        batch_op.drop_column('youtube')
        batch_op.drop_column('linkedin')

    # ### end Alembic commands ###
